name: Build Renamer
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore nuget packages
        run: dotnet restore
      - name: Build DLL
        run: dotnet build -c Release
      - uses: actions/upload-artifact@v4
        with:
          name: Renamer DLL
          path: bin/Release/net8.0/Shoko.Plugin.Renamer.dll
